### ISSUE TITLE
specify  Button (primary and secondary) shortcode options ? - and correct image

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#12]
okey!... relevant partial

```
<a href="{{ .Get 1 }}" class="button">{{ .Get 0 }}</a>
```

this means we get an array... of href and text in the button

**Comment by jhvanderschee** [comment]
we have this... see shortcodes...

**Comment by iroQuai** [comment]
Sorry a secondary button isn't mentioned in the docs..  is it possible with a shortcode?

**Comment by jhvanderschee** [comment]
No, there is no secondary button shortcode (yet).

**Comment by jhvanderschee** [comment]
I have added it in the Elements page:

```
{{< button2 "Get started for free" "/get-started/" >}}
```
