### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by mevdschee** [jhvanderschee/hugobricks#18]
To ensure that people know that they can use the repo, please add a license

**Comment by fenix011** [comment]
Umh... just made a  @jhvanderschee  <--> MIT License proposal ,
Let him double check ?

ThX for the reminder

PS: shall hugocodex get the same licensing

**Comment by mevdschee** [comment]
>MIT License proposal ,

Good proposal, MIT sounds good to me.

>PS: shall hugocodex get the same licensing , BTW ?

The snippets of hugocodex are very clearly free to use/modify, or do you mean the contents of the site?
