### ISSUE TITLE
Make first link in readme clearer

### ISSUE THREAD

**Issue by mevdschee** [jhvanderschee/hugobricks#19]
The demo link is obscured by a trailing link to the repository itself. That last link should be removed.

    [View DEMO website](https://www.hugobricks.preview.usecue.com/)
    [and get the source code here...](https://github.com/jhvanderschee/hugobricks)

Should be:

    [View DEMO website](https://www.hugobricks.preview.usecue.com/) for the code in this repository...

**Comment by fenix011** [comment]
Yep , sure... that was intentended for the Docs section, rather than on the mere README, where it's useless, indeed !

thX !
