### ISSUE TITLE
Add a video shortcode

### ISSUE THREAD

**Issue by jhvanderschee** [jhvanderschee/hugobricks#2]
We need a video shortcode that creates lightweigth compliant video embeds (Youtube, Vimeo and mp4).

**Comment by fenix011** [comment]
Hands on now...
 I plan to...
 - [x] import current layout/shortcode from hugocodex
 - [ ] polish it - make it actually 'build' without errors
 - [ ] improve it via #30 pointer


uh, something broke... (not 'pushed to the repo,yet)
```
fenix@alcyon:~/hugobricks$ hugo serve --disableFastRender
Start building sites … 
hugo v0.112.7-ea3c95a7b0f2140c248c1f40246a2e7acd2ada62 linux/amd64 BuildDate=2023-06-02T07:07:11Z VendorInfo=gohugoio
Built in 89 ms
Error: error building site: assemble: "/home/fenix/hugobricks/content/docs/shortcodes/youtubevideo.md:23:25": failed to extract shortcode: shortcode "youtubevideo" does not evaluate .Inner or .InnerDeindent, yet a closing tag was provided
```
cheers

**Comment by fenix011** [comment]
Umh... 

```
{{< youtube id="qtIqKaDlqXo" image="/uploads/youtubeposter.jpg" >}}
```
does not render the poster, but 

```
![Youtube](/uploads/youtubeposter.jpg "Youtube")
```
yes, it does render

Might be missing some shortcodes basics .. here, umh

**Comment by jhvanderschee** [comment]
I have updated it... can be closed I think.
