### ISSUE TITLE
Video shortcode

### ISSUE THREAD

**Issue by jhvanderschee** [jhvanderschee/hugobricks#30]
Inspiration > https://github.com/RoneoOrg/hugo-shortcode-roneo-collection/blob/main/layouts/shortcodes/video.html

- [x] native video file embed - html5
- [x] youtube video
- [ ] vimeo video (in progress) : 

```
{{< vimeo id="727145223" image="/uploads/resizeallimages.png" >}}
```

resources ^^ : https://hugocodex.org/add-ons/vimeo-shortcode/

**Comment by jhvanderschee** [comment]
This shortcode requires some testing.

**Comment by fenix011** [comment]
Okey !

Gonna  go for

- [ ] requires some testing 
- [ ] and a usage example - ++ doc.  now...



PS: gonna ask the guy - author (french guy) . about licensing... to that we include it, as you suggest

**Comment by jhvanderschee** [comment]
Vimeo is currently not available as a shortcode. This is postponed for now, until we have all current features documented properly.

**Comment by jhvanderschee** [comment]
I have added vimeo as a shortcode.

**Comment by fenix011** [comment]
Yup, Joost...

  I see you are Hugobicking... :-)

Let's talk tomorrow, at around 9h ?

good night !

F

Oct 31, 2024 10:55:03 PM Joost van der Schee ***@***.***>:
