### ISSUE TITLE
Audio shortcode

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#31]
[To integrate audio ...](https://roneo.org/en/hugo-audio-player-embed-remote-media-files-plyr-shortcode/)

Yay

**Comment by jhvanderschee** [comment]
https://gitlab.com/Roneo/hugo-shortcode-roneo-collection/-/blob/main/layouts/shortcodes/audio.html

**Comment by jhvanderschee** [comment]
I put it in! What is the license of this code?

**Comment by jhvanderschee** [comment]
This shortcode requires some testing, documentation and a usage example.
