### ISSUE TITLE
LEt's present some short 'how to (use)' hugobricks video-sreencasts ?

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#32]
- [x] [Video brick screencast -i : intro](https://fediverse.tv/w/5w5zeX6YJScEy7ZXunA8Pc)
- [ ] [Video brick screencast -ii : 'how to use' ](https://fediverse.tv/w/67E1y7s29r8NKeBfpzxfJM)
- [ ] [Video brick screencast -iii : 'makingof' -> update url](https://fediverse.tv/w/5w5zeX6YJScEy7ZXunA8Pc)

**Comment by fenix011** [comment]
- [x] [Audio brick screencast -i : intro update url](https://fediverse.tv/w/5w5zeX6YJScEy7ZXunA8Pc)
- [ ] [Audio brick screencast -ii : 'how to use' ->  update url](https://fediverse.tv/w/5w5zeX6YJScEy7ZXunA8Pc)
- [ ] [Audio brick screencast -iii : 'makingof' -> update url](https://fediverse.tv/w/5w5zeX6YJScEy7ZXunA8Pc)

**Comment by jhvanderschee** [comment]
Write a blog post! And create a blog post brick/layout.

**Comment by fenix011** [comment]
I'm already doing so,
On paper

Were do you want to publish it ?

Feel free,... To choose ?:
- usecue.com/blog
- hugocodex ?
- hbricks / blog ?

Let me know

Cheers

F.

Jul 7, 2023 11:36:09 AM Joost van der Schee ***@***.***>:

**Comment by fenix011** [comment]
Ah, in hbricks...you already mentioned it where

Nice

Jul 7, 2023 11:36:09 AM Joost van der Schee ***@***.***>:

**Comment by jhvanderschee** [comment]
I added the blog to the websites. You can now integrate posts/howto's there.
