### ISSUE TITLE
General 'Whishlist'

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#4]
# Hugobricks possible futures/roadmap/milestones :

Want to discuss on other more general _hugobricks_ aspects ( e.g., styling (CSS), templating, JS, deploy, ... etc) ? :

Please use this thread here ( comments below )

> Want to add some brick to the wishlist ? :
Here there is thread on [particular Hugobricks/list](https://gihtub.com/hugobricks/issues/3)

**Comment by jhvanderschee** [comment]
I have added a faq shortcode AND a FAQ brick... what is the diff? check it ou!

**Comment by fenix011** [comment]
Sure! ...haha, let's hugolego
