### ISSUE TITLE
Weird (but nice!) style effect when adding a .md image to raw content.

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#42]
_(for the record)_ 
It goes like this.... , just curious about how come to change the style so drastically ?
_(Needs further (CSS ? ) investigation from my side... )_

```---
title: Indice del Libro
image:
--- 
{{< brick_title >}}

{{< breadcrumbs >}}

# Indice del Libro

![LaLuna](/uploads/img/astrologia-lunar/moon-apollo12.jpg "LaLuna")

Preguntas frecuentes entorno a la Astrología Lunar ( y su tradición china) 

{{< /brick_title >}}
{{< brick_wide >}}

{{< faq >}}



LA LUNA ARTIFICIAL: MANUAL PARA TU CONSCIENCIA

ÍNDICE

Prólogo --------------------------------------------- pág 3

```
while, the style pattern is this other one... (before adding the .md image)  :

![image](https://github.com/jhvanderschee/hugobricks/assets/1966068/6b9232f3-eb53-4740-8532-10e54bacf40b)

Adding the the image leads to...

![image](https://github.com/jhvanderschee/hugobricks/assets/1966068/8c8427c2-b79d-4947-87a1-50fc541b444d)

**Comment by jhvanderschee** [comment]
The image should appear in the background of the title. This behaviour is a feature, not a bug.
