### ISSUE TITLE
Bug in docs when disabling the preheader

### ISSUE THREAD

**Issue by alerodrod** [jhvanderschee/hugobricks#45]
Hi 👋 

I discovered this great Hugo theme and I have a problem deactivating the preheader: on the docs section, the header and the main menu are cut off. It only happens in that section of the website.

I think it is caused by the following line, since the problem disappears if I remove it, but I don't know if deleting it could cause some other problem:

https://github.com/jhvanderschee/hugobricks/blob/3f28853f7574af3e42566de9743b232a7230fbfa/themes/hugobricks/static/css/bricks.css#L225

Thanks!

**Comment by iroQuai** [comment]
I can reproduce this bug, thanks for showing the solution :)

**Comment by jhvanderschee** [comment]
Great find! I fixed it.
