### ISSUE TITLE
Anchor links don't play nice with sticky header 

### ISSUE THREAD

**Issue by iroQuai** [jhvanderschee/hugobricks#47]
I like how it's possible to link to a specific brick on a page! Only thing is: when using a sticky header, it scrolls a tad to far so the title of the brick isn't visible anymore (as mentioned [here](https://github.com/jhvanderschee/hugobricks/issues/44#issuecomment-1739904849) )

**Comment by jhvanderschee** [comment]
I will look into this.

**Comment by jhvanderschee** [comment]
Fixed it.

**Comment by iroQuai** [comment]
Thank you!
