### ISSUE TITLE
.hugo_build.lock: too many open files

### ISSUE THREAD

**Issue by romeocontrol** [jhvanderschee/hugobricks#49]
Hallo,
working with visualStudioCode on macOS
hugo v0.118
Error: error building site: failed to acquire a build lock: open /Users/.../hugobricks/.hugo_build.lock: too many open files

Any error on my side?
Thank you for answering!
RT

**Comment by jhvanderschee** [comment]
I have never seen that before... did you manage to fix it?

**Comment by romeocontrol** [comment]
OK,
building the complete site with hugo command works w/o error.
starting the hugo server makes the error. Deleting of /.hugo_build.lock w/o effect.


imac27-2020@iMac27-2020 hugobricks % hugo
Start building sites …
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew


                   | EN
-------------------+------
  Pages            |  83
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 104
  Processed images |  60
  Aliases          |   1
  Sitemaps         |   2
  Cleaned          |   0

Total in 8807 ms


command: hugo server
Watching for changes in /Users/imac27-2020/Documents/hugo-sonnenhaus/hugobricks/{content,data,static,themes}
Watching for config changes in /Users/imac27-2020/Documents/hugo-sonnenhaus/hugobricks/config.yaml
Start building sites …
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew

Built in 0 ms
Error: error building site: failed to acquire a build lock: open /Users/imac27-2020/Documents/hugo-sonnenhaus/hugobricks/.hugo_build.lock: too many open files

**Comment by romeocontrol** [comment]
https://www.docsy.dev/docs/getting-started/#workaround
This works, but is probably not persistant.
sudo launchctl limit maxfiles 65535 200000
ulimit -n 65535
sudo sysctl -w kern.maxfiles=200000
sudo sysctl -w kern.maxfilesperproc=65535

**Comment by jhvanderschee** [comment]
Is this fixed? Seems like a Hugo bug, not theme specific...

**Comment by romeocontrol** [comment]
Hallo,
had to pause my project.
updated hugo to: hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended darwin/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=brew
error still in place
I think, it is not a hugo bug but a problem with the system due to a too large number of open files.
Wer do these many files come from?
sudo launchctl limit maxfiles 65535 200000
still helps.
Merry chrisstmas for the all of you!
RT

**Comment by marcushaupt** [comment]
Hello,

I've the same issue using MacOS 14.2.1 (23C71) and vscode on Apple Silicon. I don't have a solution for that problem. But the workaround I'm currently using is to avoid the automatic rebuild. I simply use the command: `hugo server --buildFuture --watch=false`.

This isn't ideal since you will lose one of the biggest advantages of Hugo. But at least I can use the theme, which is more important for me than having automatic rebuilds at the moment.

**Comment by Atamantra** [comment]
here is the code you should change -->

open shortcodes in layout >themes> gallery.html and replace it with this code It worked with me thanks to Mr. Joost

{{ $dir := string (.Get "dir") }}
<ul class="image-gallery">
{{ range (readDir (print "/static" $dir)) }}
  {{- $image := resources.Get (printf "%s/%s" $dir .Name) -}}
  {{- $imageurl := printf "%s/%s" $dir .Name -}}
  {{- $imagetitle := index (split .Name ".") 0 -}}
  {{- if eq $image.ResourceType "image" -}}
  <li>
    <a href="{{ ($image.Fit "1600x1600 Center q50").Permalink }}">
      <img src="{{ ($image.Fill "300x300 Center q50").Permalink }}" alt="Image {{ $imagetitle }}" />
    </a>
  </li>
  {{- end -}}
{{ end }}
</ul>

**Comment by turbolince** [comment]
> Hello,
> 
> I've the same issue using MacOS 14.2.1 (23C71) and vscode on Apple Silicon. I don't have a solution for that problem. But the workaround I'm currently using is to avoid the automatic rebuild. I simply use the command: `hugo server --buildFuture --watch=false`.
> 
> This isn't ideal since you will lose one of the biggest advantages of Hugo. But at least I can use the theme, which is more important for me than having automatic rebuilds at the moment.

This works for me too, but I wonder if there is a solution to make the autopublish with hugo server running
