### ISSUE TITLE
Restructure files so theme can be used as submodule?

### ISSUE THREAD

**Issue by iroQuai** [jhvanderschee/hugobricks#51]
With hugobricks, the demo site is also the git repo that users must clone to start a new site. I can see why this is useful: users have the most up-to-date docs downloaded and available even when offline, and the maker/owner doesn't have to maintain both a demo-site git and a theme git. 

With lots of other themes, the files in the git are structured differently, making it possible to add a theme via the git submodule function (for example: `git submodule add https://github.com/jhvanderschee/hugobricks themes/hugobricks`. )

The main benefit is that updating your own theme from the submodule git is extremely easy. With the current setup, I struggle to find a way to update my site to the latest version in an easy way. 

It's common practice to add a folder called /ExampleSite/ to the theme git, so new users can copy those files and get an understanding of how the theme works. Could this be an option for hugobricks too? Only thing is that the theme git must be seperate from the demo-site git, and an updated demo-site must be copied to the ExampleSite folder too.

Is this something you would be interested in to change?

**Comment by iroQuai** [comment]
Thinking some more about it, I realise the issue isn't supporting submodules, it is about easy updates when new bricks or bugfixes come out. The way of doing this is less important (could be via submodule, but maybe other options work just as well)

**Comment by Kayoku** [comment]
Just a push for this issue, I want to create my site with hugobricks, but it seems difficult with submodule method.

**Comment by jhvanderschee** [comment]
I have fixed this by having a checkout of the repo and then overwriting the theme folder... with the theme folder from the checked out repo. Does that work for you?

**Comment by iroQuai** [comment]
This doesn't sound too difficult, although I'm not familiar enough with git to understand what I should do. Could you point me in the right direction? Step-by-step explanation would be best ofcourse;)

I've noticed your Dutch, like me. If you want, you can send me a quick explanation in dutch. When I get to trying it out, I then can make a more detailed guide in English to add to the docs. 

Or is this only a quick workaround and do you see benefits in supporting a more standard way of updating/Installing for your theme, like said submodules? If so, it would be more valuable if i use my time to help restructuring the files

**Comment by Kayoku** [comment]
If I understand you well @jhvanderschee , you have two different branch :
- One branch which if a fork of the current repo (hugobricks theme)
- One branch with the true data of your current website, and you "checkout" the specific theme folder from the other branch to this branch

Am I correct ?

**Comment by jhvanderschee** [comment]
Yes, correct.

**Comment by Kayoku** [comment]
Ok thanks ! 

@iroQuai I should be able to give you a cheatsheet about how to do it. I'll try it first and I'll be back to let you know

**Comment by Kayoku** [comment]
Hi ! Ok so, after some test I successfully set it up. I just want to warn you, even if it's working, I'm not sure that this is the best way to handle theming in Hugo. But let's do it :-)

- First, create your personal Hugo Site project in Gitlab/Github with a basic README.
- Clone the new repository in local : `git clone <YOUR_REPO>`
- Create a new empty branch named `hugobricks`, put yourself in this branch and delete the `README.md` from this branch to avoid future conflict : `git checkout --orphan hugobricks ; git rm --cache README.md`
This branch will be used to follow the official hugobricks repository.
- Then, add the remote official Hugobricks Github repository to your project : `git remote add hugobricks-official https://github.com/jhvanderschee/hugobricks`
Now when you check with `git remote -v`, you should see something similar to :
```
hugobricks	https://github.com/jhvanderschee/hugobricks (fetch)
hugobricks	https://github.com/jhvanderschee/hugobricks (push)
origin	https://gitlab.com/xxx/mysite (fetch)
origin	https://gitlab.com/xxx/mysite (push)
```
- Now, we can get all the official repository to our local repo : `git pull hugobricks-official main` (`hugobricks-official` allow to specify that your target is your repository, and `main` specify the branch being used on the target)
- Then, push it to your repository : `git push origin hugobricks` (same as before for the explaination)
- Now, get back to the `main` branch of our local repo : `git checkout main`
- Then, checkout just the themes folder from the other branch : `git checkout hugobricks -- themes` (inspired by [this link](https://stackoverflow.com/questions/4479960/git-checkout-to-a-specific-folder))
- Add, Commit, and finally push the new modification : `git push origin main`

Tadaaa ! Everything is working :-)

if you want to update the theme, now you just have to checkout to the `hugobricks` branch, pull the new change, push it to your repo, re-checkout to your main branch, then checkout the themes folder like we did before.

Hope it help you, don't hesitate if you have any question.
And happy new year :D

**Comment by jhvanderschee** [comment]
I do not recommend to update Hugobricks. You might find that changes are breaking your carefully created website. I would cherry-pick if you need features. The fun about static sites is that they do not break when you do not change them. Unless you have a very good reason, I would not update to the latest version.

**Comment by iroQuai** [comment]
Hmmm that's an interesting take! One of the reasons I'd like to be able to update Hugobricks is that those updates usually fix various issues! 

I haven't tried cherrypicking only the updates that fix the issues I activly run in too. I guess that would be harder than I'd like it to be since that'll probably mean I have to edit the (sometimes several) files myself, not always understanding the effect it has on other parts of the site. 

(Sure if I was a Hugo developer or website builder by profession that probably wouldn't be so hard for me, but I'm just a hobbyist!)

**Comment by pasdengl** [comment]
I pull hugobricks into `deps/hugobricks` as a submodule and copy over the files I need via a `Makefile`. A minimal example looks like this:

```Makefile
.PHONY: init
init: deps/hugobricks/.git

deps/hugobricks/.git:
	git submodule update --init

themes/hugobricks/: deps/hugobricks/themes/hugobricks/
	@mkdir -p $@
	@cp -r $</i18n $</layouts $</static $@

static/: deps/hugobricks/static/
	@mkdir -p $@
	@cp -r $</css static/
	@cp -r $</uploads/ static/uploads/

.PHONY: all
all: themes/hugobricks/ static/

clean: clean
	$(RM) -r static
	$(RM) -r themes
	$(RM) -r public
	$(RM) -r resources
	git submodule deinit --all
```

With this I do not have to track the copied files in git separately but rather copy them at build time. It also allows me to pull updates via `git submodule update --init --remote` and commit the updated submodule in case everything runs smoothly.
