### ISSUE TITLE
Image Alt Text

### ISSUE THREAD

**Issue by C4E5G3** [jhvanderschee/hugobricks#56]
Super theme. The font is great.

I am struggling with some of the features.....

I replaced the render-link.html code with the blank_target code....but my links still open in page....

The map template has a black marker that I cannot get rid of...
 

Also:
What is this notation for? 
{{</* brick_features */>}}{{</* /brick_features */>}}

How does the 'openinghours' shortcode work?

**Comment by jhvanderschee** [comment]
Font choice by Zeon Studios: https://github.com/jhvanderschee/hugobricks/?tab=readme-ov-file#credits-and-licenses

**Comment by jhvanderschee** [comment]
To remove the marker, just add this to the css:

```
.map:not(section)::after {display: none!important;}
```

**Comment by jhvanderschee** [comment]
```
{{</* brick_features />}}{{</ /brick_features */>}}
```
This notation is used to display the shortcode without executing it (in the docs).

**Comment by jhvanderschee** [comment]
> How does the 'openinghours' shortcode work?

There is no shortcode for that (yet).
