### ISSUE TITLE
hugobricks doc ( under construction )

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#6]
yep! In the making ...cooking :

[hugobricks doc.- SKELETON](https://gist.github.com/fenix011/dc708651b1b105e1a32e7f6ade956af6)  Umh...(nested menus ... à-la hugocodex.org  add-on  ...  ) makingof

#### to be hugocodexed upon the 'nested menu' add-on way...

(Writing the content now...)
	 Umh,... 
	 Let's see if i can get it embedded in the hugobricks repo by tomorrow ... doubting about the into the (hugobricks)  menu embedding'...
 Articulating the nesting/branches onto the existing menu sctructure.
	 
  I'll figure it out... after some `<code dreaming />` tonight :-P ?

PS: i've found GH gist useful... (as long as you might want to embed/clone... some gist one day?)

**Comment by jhvanderschee** [comment]
First version created.
