### ISSUE TITLE
Error: add site dependencies: load resources: loading templates: "/home/me/projects/hugo/hugobricks/themes/hugobricks/layouts/partials/breadcrumbs.html:2:1": parse failed: template: partials/breadcrumbs.html:2: function "page" not defined

### ISSUE THREAD

**Issue by danfmihai** [jhvanderschee/hugobricks#63]
How do I install exactly step by step? I get this error when I run hugo server:
`Error: add site dependencies: load resources: loading templates: "/home/me/projects/hugo/hugobricks/themes/hugobricks/layouts/partials/breadcrumbs.html:2:1": parse failed: template: partials/breadcrumbs.html:2: function "page" not defined`

**Comment by jhvanderschee** [comment]
Just clone the whole thing and type `hugo server`.
