### ISSUE TITLE
Nested-menu docs widget doesn't show up

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#7]
Yep !

  While working in the (nested menu) docs area (widget) 

- [x] made the content/branches - doc folders ...
- [x] brought the needed layouts/partials
- [ ] the method i use for embedding the widget  as a partial \!/  fails   : 

```
# About Lorem..
[..]
## And...yes: there is project documentation available

{{ partial "nested-menu.html" . }}  \!/ this fails to load 

```

in the about.md file

...umh,i might be missing some very basics here... ? (Not gonna push the tests/changes, for now...FYI)

I might be calling the relevant partial in the 'wrong place' ?

**Comment by jhvanderschee** [comment]
4 out of 3 times it is a matter of having the wrong context...

**Comment by jhvanderschee** [comment]
Fixed.
